services:
#   api:
#     build:
#       context: ./api
#       dockerfile: Dockerfile
#       target: api
#     environment:
#       APP_ENV: development
#       APP_PORT: 2910
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_NAME: omnilogs
#       DB_USERNAME: postgres
#       DB_PASSWORD: admin
#       JWT_SECRET: development-secret
#       DATA_ENCRYPTION_KEY: abcdefghijklmnopqrstuvwxyz123456
#       ACCESS_TOKEN_EXPIRE_SECONDS: 900
#       REFRESH_TOKEN_EXPIRE_SECONDS: 604800
#       SWAGGER_ENABLED: "true"
#       ELASTICSEARCH_URL: http://elasticsearch:9200
#     depends_on:
#       - postgres
#       - elasticsearch
#     ports:
#       - "2910:2910"

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: worker
    environment:
      APP_ENV: development
      APP_PORT: 2911
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: omnilogs
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      JWT_SECRET: development-secret
      DATA_ENCRYPTION_KEY: abcdefghijklmnopqrstuvwxyz123456
      ACCESS_TOKEN_EXPIRE_SECONDS: 900
      REFRESH_TOKEN_EXPIRE_SECONDS: 604800
      SWAGGER_ENABLED: "false"
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    image: postgres:16
    container_name: omnilogs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: omnilogs
    ports:
      - "5499:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: omnilogs-elastic
    hostname: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
    name: omnilogs-demo_postgres_data
    external: true
  elastic_data:
    name: omnilogs-demo_elastic_data
    external: true
