CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar NOT NULL,
  "product_code" varchar UNIQUE NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "product_environments" (
  "environment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "environment_code" varchar NOT NULL,
  "environment_name" varchar NOT NULL,
  "created_at" timestamptz
);

CREATE TABLE "product_api_keys" (
  "key_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "environment_id" int,
  "key_name" varchar,
  "key_prefix" varchar NOT NULL,
  "key_hash" varchar NOT NULL,
  "permissions" jsonb NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_used_at" timestamptz,
  "expires_at" timestamptz,
  "revoked_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "projects" (
  "project_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "project_code" varchar NOT NULL,
  "project_name" varchar NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "project_features" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "project_id" int NOT NULL,
  "parent_id" int,
  "category_type" varchar,
  "category_code" varchar NOT NULL,
  "category_name" varchar NOT NULL,
  "full_path" varchar,
  "path_ids" varchar,
  "level" int NOT NULL DEFAULT 1,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "phone_number" varchar,
  "password_hash" varchar,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_login_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "deleted_at" timestamptz
);

CREATE TABLE "role_templates" (
  "template_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_code" varchar UNIQUE NOT NULL,
  "role_name" varchar NOT NULL,
  "description" text,
  "is_system_template" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "platform_roles" (
  "platform_role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_code" varchar UNIQUE NOT NULL,
  "role_name" varchar NOT NULL,
  "description" text,
  "permissions" jsonb NOT NULL,
  "is_system_role" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "platform_memberships" (
  "platform_membership_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "platform_role_id" int NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "expires_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "product_roles" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "template_id" int,
  "role_code" varchar NOT NULL,
  "role_name" varchar NOT NULL,
  "permissions" jsonb NOT NULL,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "product_memberships" (
  "membership_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "role_id" int NOT NULL,
  "expires_at" timestamptz,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "product_membership_scopes" (
  "scope_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "membership_id" int NOT NULL,
  "product_id" int NOT NULL,
  "project_id" int,
  "category_id" int,
  "scope_level" varchar NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "user_role_permission_rules" (
  "permission_rule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int,
  "role_id" int,
  "project_id" int,
  "category_id" int,
  "resource_type" varchar NOT NULL,
  "action" varchar NOT NULL,
  "effect" varchar NOT NULL,
  "scope_level" varchar NOT NULL,
  "granted_by" int,
  "is_active" boolean NOT NULL DEFAULT true,
  "expires_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_sources" (
  "source_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "source_code" varchar NOT NULL,
  "source_name" varchar NOT NULL,
  "source_type" varchar NOT NULL DEFAULT 'UNKNOWN',
  "source_platform" varchar NOT NULL DEFAULT 'UNKNOWN',
  "runtime_name" varchar,
  "sdk_name" varchar,
  "sdk_version" varchar,
  "discovery_status" varchar NOT NULL DEFAULT 'AUTO_DISCOVERED',
  "created_by_source" varchar NOT NULL DEFAULT 'SYSTEM',
  "first_seen_at" timestamptz,
  "last_seen_at" timestamptz,
  "description" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_ingestion_policies" (
  "policy_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "environment_id" int NOT NULL,
  "max_logs_per_minute" int,
  "max_batch_size" int,
  "flush_interval_seconds" int,
  "max_retries" int,
  "retry_interval_seconds" int,
  "queue_enabled" boolean NOT NULL DEFAULT true,
  "queue_worker_enabled" boolean NOT NULL DEFAULT true,
  "queue_lock_timeout_seconds" int NOT NULL DEFAULT 600,
  "strict_ordering_enabled" boolean NOT NULL DEFAULT true,
  "retention_days" int,
  "archive_enabled" boolean NOT NULL DEFAULT false,
  "archive_format" varchar,
  "archive_storage_path" text,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_masking_rules" (
  "masking_rule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "field_key" varchar,
  "field_path" varchar,
  "match_type" varchar,
  "mask_type" varchar,
  "mask_value" varchar,
  "secret_handling_mode" varchar NOT NULL DEFAULT 'MASK_ONLY',
  "encryption_required" boolean NOT NULL DEFAULT false,
  "view_requires_password" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_field_definitions" (
  "field_definition_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "project_id" int,
  "category_id" int,
  "field_key" varchar NOT NULL,
  "display_name" varchar,
  "description" text,
  "source_section" varchar NOT NULL,
  "field_path" varchar,
  "elastic_field_name" varchar NOT NULL,
  "data_type" varchar NOT NULL,
  "value_source_type" varchar NOT NULL DEFAULT 'NONE',
  "value_source_key" varchar,
  "is_required" boolean NOT NULL DEFAULT false,
  "is_sensitive" boolean NOT NULL DEFAULT false,
  "mask_before_index" boolean NOT NULL DEFAULT false,
  "encrypt_before_archive" boolean NOT NULL DEFAULT false,
  "is_visible" boolean NOT NULL DEFAULT true,
  "is_searchable" boolean NOT NULL DEFAULT false,
  "is_filterable" boolean NOT NULL DEFAULT false,
  "is_sortable" boolean NOT NULL DEFAULT false,
  "is_aggregatable" boolean NOT NULL DEFAULT false,
  "display_order" int,
  "default_value" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_field_enum_options" (
  "option_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field_definition_id" int NOT NULL,
  "option_key" varchar NOT NULL,
  "option_label" varchar NOT NULL,
  "option_value" varchar NOT NULL,
  "display_order" int,
  "is_default" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_field_value_sources" (
  "value_source_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field_definition_id" int NOT NULL,
  "source_type" varchar NOT NULL,
  "source_key" varchar NOT NULL,
  "source_config" jsonb,
  "label_field" varchar,
  "value_field" varchar,
  "is_required" boolean NOT NULL DEFAULT false,
  "timeout_seconds" int,
  "refresh_mode" varchar NOT NULL DEFAULT 'ON_DEMAND',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_queue_batches" (
  "batch_id" uuid PRIMARY KEY,
  "product_id" int,
  "source_id" int,
  "environment_id" int,
  "queue_key" varchar NOT NULL,
  "source_type" varchar NOT NULL DEFAULT 'UNKNOWN',
  "source_platform" varchar NOT NULL DEFAULT 'UNKNOWN',
  "source_ip" varchar,
  "user_agent" text,
  "idempotency_key" varchar,
  "detected_product_code" varchar,
  "product_resolution_status" varchar NOT NULL DEFAULT 'RESOLVED',
  "product_resolution_reason" text,
  "product_resolved_at" timestamptz,
  "available_at" timestamptz,
  "worker_id" varchar,
  "processing_attempts" int NOT NULL DEFAULT 0,
  "total_logs" int NOT NULL DEFAULT 0,
  "status" varchar NOT NULL DEFAULT 'QUEUED',
  "priority" int NOT NULL DEFAULT 0,
  "received_at" timestamptz,
  "processing_started_at" timestamptz,
  "processed_at" timestamptz,
  "retention_until" timestamptz,
  "purged_at" timestamptz,
  "locked_by" varchar,
  "locked_at" timestamptz,
  "error_message" text,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_queue_items" (
  "queue_item_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_id" uuid NOT NULL,
  "sequence_no" int NOT NULL,
  "source_type" varchar NOT NULL DEFAULT 'UNKNOWN',
  "source_platform" varchar NOT NULL DEFAULT 'UNKNOWN',
  "input_payload" jsonb,
  "payload_size_bytes" bigint,
  "payload_purged" boolean NOT NULL DEFAULT false,
  "detected_product_code" varchar,
  "worker_id" varchar,
  "processing_attempts" int NOT NULL DEFAULT 0,
  "status" varchar NOT NULL DEFAULT 'PENDING',
  "retry_count" int NOT NULL DEFAULT 0,
  "max_retry_count" int NOT NULL DEFAULT 3,
  "next_retry_at" timestamptz,
  "last_retry_at" timestamptz,
  "processing_started_at" timestamptz,
  "processed_at" timestamptz,
  "error_message" text,
  "retention_until" timestamptz,
  "purged_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_failures" (
  "failure_id" uuid PRIMARY KEY,
  "attempt_no" int NOT NULL DEFAULT 1,
  "queue_item_id" bigint NOT NULL,
  "batch_id" uuid NOT NULL,
  "product_id" int,
  "source_id" int,
  "environment_id" int,
  "failure_stage" varchar NOT NULL,
  "failure_type" varchar NOT NULL,
  "reason" text,
  "error_details" jsonb,
  "retry_count" int NOT NULL DEFAULT 0,
  "max_retry_count" int NOT NULL DEFAULT 3,
  "next_retry_at" timestamptz,
  "last_retry_at" timestamptz,
  "status" varchar NOT NULL DEFAULT 'FAILED',
  "created_at" timestamptz,
  "resolved_at" timestamptz
);

CREATE TABLE "system_audit_logs" (
  "audit_id" uuid PRIMARY KEY,
  "user_id" int,
  "product_id" int,
  "action" varchar NOT NULL,
  "method" varchar,
  "url" text,
  "ip_address" varchar,
  "query_json" jsonb,
  "payload" jsonb,
  "created_at" timestamptz
);

CREATE TABLE "sensitive_log_access_requests" (
  "request_id" uuid PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "log_id" uuid,
  "field_definition_id" int,
  "secret_id" uuid,
  "field_path" varchar,
  "reason" text,
  "approval_status" varchar NOT NULL,
  "approved_by" int,
  "approved_at" timestamptz,
  "expires_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_sensitive_field_secrets" (
  "secret_id" uuid PRIMARY KEY,
  "log_id" uuid NOT NULL,
  "product_id" int NOT NULL,
  "project_id" int,
  "category_id" int,
  "environment_id" int,
  "field_definition_id" int,
  "field_key" varchar NOT NULL,
  "field_path" varchar NOT NULL,
  "source_section" varchar NOT NULL,
  "value_hash" varchar,
  "encrypted_value" text NOT NULL,
  "encryption_key_ref" varchar,
  "encryption_algorithm" varchar,
  "requires_approval" boolean NOT NULL DEFAULT true,
  "retention_until" timestamptz,
  "purged_at" timestamptz,
  "created_at" timestamptz
);

CREATE TABLE "sensitive_log_access_history" (
  "access_id" uuid PRIMARY KEY,
  "request_id" uuid,
  "product_id" int,
  "user_id" int NOT NULL,
  "project_id" int,
  "category_id" int,
  "log_id" uuid,
  "field_path" varchar,
  "access_reason" text,
  "auth_method" varchar,
  "access_status" varchar,
  "created_at" timestamptz
);

CREATE TABLE "log_archives" (
  "archive_id" uuid PRIMARY KEY,
  "product_id" int NOT NULL,
  "environment_id" int,
  "project_id" int,
  "archive_year" int NOT NULL,
  "archive_month" int NOT NULL,
  "date_from" timestamptz,
  "date_to" timestamptz,
  "storage_provider" varchar NOT NULL DEFAULT 'GCS',
  "bucket_name" varchar,
  "file_path" text,
  "file_format" varchar,
  "total_logs" int,
  "compressed_size_bytes" bigint,
  "checksum" varchar,
  "status" varchar,
  "exported_at" timestamptz,
  "restored_at" timestamptz,
  "purged_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "elastic_index_policies" (
  "elastic_policy_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "environment_id" int,
  "index_prefix" varchar NOT NULL,
  "index_pattern" varchar,
  "write_alias" varchar,
  "rollover_type" varchar NOT NULL DEFAULT 'MONTHLY',
  "number_of_shards" int NOT NULL DEFAULT 1,
  "number_of_replicas" int NOT NULL DEFAULT 1,
  "retention_days" int,
  "schema_version" varchar NOT NULL DEFAULT 'v1',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_index_refs" (
  "log_id" uuid PRIMARY KEY,
  "product_id" int NOT NULL,
  "project_id" int,
  "category_id" int,
  "environment_id" int NOT NULL,
  "source_id" int,
  "batch_id" uuid,
  "queue_item_id" bigint,
  "response_status_code" int,
  "duration_ms" int,
  "log_level" varchar,
  "event_type" varchar,
  "source_request_id" varchar,
  "correlation_id" varchar,
  "trace_id" varchar,
  "span_id" varchar,
  "parent_span_id" varchar,
  "request_method" varchar,
  "request_path" text,
  "route_pattern" text,
  "feature_full_path" text,
  "feature_path_ids" varchar,
  "timestamp" timestamptz NOT NULL,
  "ingested_at" timestamptz,
  "elastic_index" varchar NOT NULL,
  "elastic_document_id" varchar NOT NULL,
  "index_status" varchar NOT NULL DEFAULT 'PENDING',
  "indexed_at" timestamptz,
  "last_sync_at" timestamptz,
  "sync_error" text,
  "is_archived" boolean NOT NULL DEFAULT false,
  "archived_at" timestamptz,
  "deleted_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "log_object_storage_refs" (
  "object_ref_id" uuid PRIMARY KEY,
  "log_id" uuid NOT NULL,
  "product_id" int NOT NULL,
  "environment_id" int,
  "storage_provider" varchar NOT NULL DEFAULT 'GCS',
  "bucket_name" varchar,
  "object_path" text NOT NULL,
  "object_type" varchar NOT NULL,
  "file_format" varchar,
  "size_bytes" bigint,
  "checksum" varchar,
  "is_encrypted" boolean NOT NULL DEFAULT false,
  "retention_until" timestamptz,
  "purged_at" timestamptz,
  "created_at" timestamptz
);

CREATE UNIQUE INDEX ON "product_environments" ("product_id", "environment_code");

CREATE UNIQUE INDEX ON "product_api_keys" ("key_hash");

CREATE INDEX ON "product_api_keys" ("product_id", "environment_id", "is_active");

CREATE INDEX ON "product_api_keys" ("key_prefix");

CREATE UNIQUE INDEX ON "projects" ("product_id", "project_code");

CREATE UNIQUE INDEX ON "project_features" ("product_id", "project_id", "category_code");

CREATE INDEX ON "project_features" ("product_id", "project_id", "full_path");

CREATE INDEX ON "project_features" ("project_id", "parent_id");

CREATE UNIQUE INDEX ON "platform_memberships" ("user_id", "platform_role_id");

CREATE UNIQUE INDEX ON "product_roles" ("role_id", "product_id");

CREATE UNIQUE INDEX ON "product_roles" ("product_id", "role_code");

CREATE UNIQUE INDEX ON "product_memberships" ("user_id", "product_id", "role_id");

CREATE INDEX ON "product_memberships" ("product_id", "is_active");

CREATE UNIQUE INDEX ON "product_membership_scopes" ("membership_id", "product_id", "project_id", "category_id");

CREATE INDEX ON "product_membership_scopes" ("product_id", "project_id", "category_id");

CREATE UNIQUE INDEX ON "user_role_permission_rules" ("user_id", "product_id", "role_id", "project_id", "category_id", "resource_type", "action");

CREATE INDEX ON "user_role_permission_rules" ("user_id", "is_active");

CREATE INDEX ON "user_role_permission_rules" ("product_id", "user_id");

CREATE INDEX ON "user_role_permission_rules" ("role_id", "user_id");

CREATE INDEX ON "user_role_permission_rules" ("resource_type", "action");

CREATE INDEX ON "user_role_permission_rules" ("effect");

CREATE UNIQUE INDEX ON "log_sources" ("product_id", "source_code");

CREATE INDEX ON "log_sources" ("product_id", "source_type");

CREATE INDEX ON "log_sources" ("product_id", "source_platform");

CREATE INDEX ON "log_sources" ("discovery_status");

CREATE INDEX ON "log_sources" ("product_id", "is_active");

CREATE UNIQUE INDEX ON "log_ingestion_policies" ("product_id", "environment_id");

CREATE INDEX ON "log_masking_rules" ("product_id", "is_active");

CREATE INDEX ON "log_masking_rules" ("product_id", "field_key");

CREATE INDEX ON "log_masking_rules" ("product_id", "field_path");

CREATE INDEX ON "log_masking_rules" ("product_id", "secret_handling_mode");

CREATE UNIQUE INDEX ON "log_field_definitions" ("product_id", "project_id", "category_id", "field_key");

CREATE INDEX ON "log_field_definitions" ("product_id", "is_active");

CREATE INDEX ON "log_field_definitions" ("value_source_type", "value_source_key");

CREATE INDEX ON "log_field_definitions" ("source_section", "field_path");

CREATE INDEX ON "log_field_definitions" ("elastic_field_name");

CREATE INDEX ON "log_field_definitions" ("is_searchable");

CREATE INDEX ON "log_field_definitions" ("is_filterable");

CREATE INDEX ON "log_field_definitions" ("is_aggregatable");

CREATE UNIQUE INDEX ON "log_field_enum_options" ("field_definition_id", "option_key");

CREATE INDEX ON "log_field_enum_options" ("field_definition_id", "is_active");

CREATE INDEX ON "log_field_enum_options" ("field_definition_id", "display_order");

CREATE UNIQUE INDEX ON "log_field_value_sources" ("field_definition_id", "source_key");

CREATE INDEX ON "log_field_value_sources" ("source_type", "source_key");

CREATE INDEX ON "log_field_value_sources" ("field_definition_id", "is_active");

CREATE INDEX ON "log_field_value_sources" ("is_active");

CREATE INDEX ON "log_queue_batches" ("queue_key", "status", "received_at");

CREATE INDEX ON "log_queue_batches" ("product_id", "environment_id", "status", "received_at");

CREATE INDEX ON "log_queue_batches" ("source_type", "source_platform", "status", "received_at");

CREATE INDEX ON "log_queue_batches" ("product_resolution_status", "status", "received_at");

CREATE INDEX ON "log_queue_batches" ("detected_product_code");

CREATE INDEX ON "log_queue_batches" ("product_id", "source_id", "received_at");

CREATE UNIQUE INDEX ON "log_queue_batches" ("idempotency_key");

CREATE INDEX ON "log_queue_batches" ("locked_at");

CREATE INDEX ON "log_queue_batches" ("status", "retention_until");

CREATE INDEX ON "log_queue_batches" ("purged_at");

CREATE INDEX ON "log_queue_batches" ("available_at", "status");

CREATE INDEX ON "log_queue_batches" ("status", "available_at", "priority");

CREATE INDEX ON "log_queue_batches" ("worker_id");

CREATE UNIQUE INDEX ON "log_queue_items" ("batch_id", "sequence_no");

CREATE INDEX ON "log_queue_items" ("batch_id", "status", "sequence_no");

CREATE INDEX ON "log_queue_items" ("source_type", "source_platform", "status");

CREATE INDEX ON "log_queue_items" ("status", "next_retry_at");

CREATE INDEX ON "log_queue_items" ("detected_product_code");

CREATE INDEX ON "log_queue_items" ("status", "retention_until");

CREATE INDEX ON "log_queue_items" ("payload_purged", "retention_until");

CREATE INDEX ON "log_queue_items" ("purged_at");

CREATE INDEX ON "log_queue_items" ("worker_id");

CREATE INDEX ON "log_queue_items" ("status", "retry_count");

CREATE UNIQUE INDEX ON "log_failures" ("queue_item_id", "attempt_no");

CREATE INDEX ON "log_failures" ("batch_id");

CREATE INDEX ON "log_failures" ("product_id", "status", "next_retry_at");

CREATE INDEX ON "log_failures" ("environment_id", "status", "created_at");

CREATE INDEX ON "log_failures" ("failure_stage", "failure_type");

CREATE INDEX ON "log_failures" ("status", "next_retry_at");

CREATE INDEX ON "system_audit_logs" ("user_id", "created_at");

CREATE INDEX ON "system_audit_logs" ("product_id", "created_at");

CREATE INDEX ON "system_audit_logs" ("action", "created_at");

CREATE INDEX ON "sensitive_log_access_requests" ("user_id", "product_id", "approval_status");

CREATE INDEX ON "sensitive_log_access_requests" ("log_id");

CREATE INDEX ON "sensitive_log_access_requests" ("field_definition_id");

CREATE INDEX ON "sensitive_log_access_requests" ("secret_id");

CREATE INDEX ON "sensitive_log_access_requests" ("approval_status", "expires_at");

CREATE INDEX ON "log_sensitive_field_secrets" ("log_id");

CREATE INDEX ON "log_sensitive_field_secrets" ("product_id", "field_key");

CREATE INDEX ON "log_sensitive_field_secrets" ("field_definition_id");

CREATE INDEX ON "log_sensitive_field_secrets" ("value_hash");

CREATE INDEX ON "log_sensitive_field_secrets" ("source_section");

CREATE INDEX ON "log_sensitive_field_secrets" ("retention_until");

CREATE INDEX ON "log_sensitive_field_secrets" ("purged_at");

CREATE INDEX ON "sensitive_log_access_history" ("product_id", "user_id", "created_at");

CREATE INDEX ON "sensitive_log_access_history" ("log_id");

CREATE INDEX ON "sensitive_log_access_history" ("access_status", "created_at");

CREATE INDEX ON "log_archives" ("product_id", "environment_id", "project_id", "archive_year", "archive_month");

CREATE INDEX ON "log_archives" ("status");

CREATE INDEX ON "log_archives" ("date_from", "date_to");

CREATE UNIQUE INDEX ON "elastic_index_policies" ("product_id", "environment_id");

CREATE UNIQUE INDEX ON "elastic_index_policies" ("index_prefix");

CREATE UNIQUE INDEX ON "elastic_index_policies" ("write_alias");

CREATE INDEX ON "elastic_index_policies" ("is_active");

CREATE INDEX ON "log_index_refs" ("product_id", "timestamp");

CREATE INDEX ON "log_index_refs" ("product_id", "project_id", "timestamp");

CREATE INDEX ON "log_index_refs" ("product_id", "category_id", "timestamp");

CREATE INDEX ON "log_index_refs" ("environment_id", "timestamp");

CREATE INDEX ON "log_index_refs" ("source_id", "timestamp");

CREATE INDEX ON "log_index_refs" ("batch_id");

CREATE INDEX ON "log_index_refs" ("queue_item_id");

CREATE INDEX ON "log_index_refs" ("source_request_id");

CREATE INDEX ON "log_index_refs" ("correlation_id");

CREATE INDEX ON "log_index_refs" ("trace_id");

CREATE INDEX ON "log_index_refs" ("product_id", "source_request_id");

CREATE INDEX ON "log_index_refs" ("product_id", "correlation_id");

CREATE INDEX ON "log_index_refs" ("product_id", "trace_id");

CREATE INDEX ON "log_index_refs" ("product_id", "request_method");

CREATE INDEX ON "log_index_refs" ("product_id", "route_pattern");

CREATE INDEX ON "log_index_refs" ("product_id", "category_id", "route_pattern");

CREATE UNIQUE INDEX ON "log_index_refs" ("elastic_index", "elastic_document_id");

CREATE INDEX ON "log_index_refs" ("index_status", "updated_at");

CREATE INDEX ON "log_index_refs" ("is_archived", "timestamp");

CREATE INDEX ON "log_object_storage_refs" ("log_id");

CREATE INDEX ON "log_object_storage_refs" ("product_id", "environment_id");

CREATE INDEX ON "log_object_storage_refs" ("object_type");

CREATE INDEX ON "log_object_storage_refs" ("retention_until");

CREATE INDEX ON "log_object_storage_refs" ("purged_at");

COMMENT ON TABLE "log_queue_batches" IS 'ใช้เป็นหัวคิวของ log batch รองรับ log จาก client, server, web, webapp, application, android, ios และ cloud logs';

COMMENT ON TABLE "log_queue_items" IS 'ใช้เป็น queue item ราย log ก่อน validate, transform, mask, enrich, index เข้า Elasticsearch และบันทึก reference เข้า log_index_refs';

COMMENT ON TABLE "log_failures" IS 'เก็บรายการ log ที่ process ไม่สำเร็จ โดยเฉพาะ validate, transform, masking, index เข้า Elastic และ save reference';

COMMENT ON TABLE "log_index_refs" IS 'Postgres เก็บเฉพาะ reference และ metadata สำคัญของ log ที่อยู่ใน Elasticsearch เช่น request id, trace id, route path และ feature path snapshot';

COMMENT ON TABLE "log_object_storage_refs" IS 'เก็บ reference ไปยัง raw log หรือ payload ขนาดใหญ่ที่อยู่นอก Postgres เช่น GCS';

ALTER TABLE "product_environments" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_api_keys" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_api_keys" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projects" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_features" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_features" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_features" ADD FOREIGN KEY ("parent_id") REFERENCES "project_features" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "platform_memberships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "platform_memberships" ADD FOREIGN KEY ("platform_role_id") REFERENCES "platform_roles" ("platform_role_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_roles" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_roles" ADD FOREIGN KEY ("template_id") REFERENCES "role_templates" ("template_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_memberships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_memberships" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_memberships" ADD FOREIGN KEY ("role_id") REFERENCES "product_roles" ("role_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_membership_scopes" ADD FOREIGN KEY ("membership_id") REFERENCES "product_memberships" ("membership_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_membership_scopes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_membership_scopes" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_membership_scopes" ADD FOREIGN KEY ("category_id") REFERENCES "project_features" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_permission_rules" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_permission_rules" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_permission_rules" ADD FOREIGN KEY ("role_id") REFERENCES "product_roles" ("role_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_permission_rules" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_permission_rules" ADD FOREIGN KEY ("category_id") REFERENCES "project_features" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_permission_rules" ADD FOREIGN KEY ("granted_by") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_sources" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_ingestion_policies" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_ingestion_policies" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_masking_rules" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_field_definitions" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_field_definitions" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_field_definitions" ADD FOREIGN KEY ("category_id") REFERENCES "project_features" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_field_enum_options" ADD FOREIGN KEY ("field_definition_id") REFERENCES "log_field_definitions" ("field_definition_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_field_value_sources" ADD FOREIGN KEY ("field_definition_id") REFERENCES "log_field_definitions" ("field_definition_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_queue_batches" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_queue_batches" ADD FOREIGN KEY ("source_id") REFERENCES "log_sources" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_queue_batches" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_queue_items" ADD FOREIGN KEY ("batch_id") REFERENCES "log_queue_batches" ("batch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_failures" ADD FOREIGN KEY ("queue_item_id") REFERENCES "log_queue_items" ("queue_item_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_failures" ADD FOREIGN KEY ("batch_id") REFERENCES "log_queue_batches" ("batch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_failures" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_failures" ADD FOREIGN KEY ("source_id") REFERENCES "log_sources" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_failures" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "system_audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "system_audit_logs" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_requests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_requests" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_requests" ADD FOREIGN KEY ("log_id") REFERENCES "log_index_refs" ("log_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_requests" ADD FOREIGN KEY ("field_definition_id") REFERENCES "log_field_definitions" ("field_definition_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_requests" ADD FOREIGN KEY ("secret_id") REFERENCES "log_sensitive_field_secrets" ("secret_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_requests" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_sensitive_field_secrets" ADD FOREIGN KEY ("log_id") REFERENCES "log_index_refs" ("log_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_sensitive_field_secrets" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_sensitive_field_secrets" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_sensitive_field_secrets" ADD FOREIGN KEY ("category_id") REFERENCES "project_features" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_sensitive_field_secrets" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_sensitive_field_secrets" ADD FOREIGN KEY ("field_definition_id") REFERENCES "log_field_definitions" ("field_definition_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_history" ADD FOREIGN KEY ("request_id") REFERENCES "sensitive_log_access_requests" ("request_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_history" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_history" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_history" ADD FOREIGN KEY ("category_id") REFERENCES "project_features" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sensitive_log_access_history" ADD FOREIGN KEY ("log_id") REFERENCES "log_index_refs" ("log_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_archives" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_archives" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_archives" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "elastic_index_policies" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "elastic_index_policies" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_index_refs" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_index_refs" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_index_refs" ADD FOREIGN KEY ("category_id") REFERENCES "project_features" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_index_refs" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_index_refs" ADD FOREIGN KEY ("source_id") REFERENCES "log_sources" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_index_refs" ADD FOREIGN KEY ("batch_id") REFERENCES "log_queue_batches" ("batch_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_index_refs" ADD FOREIGN KEY ("queue_item_id") REFERENCES "log_queue_items" ("queue_item_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_object_storage_refs" ADD FOREIGN KEY ("log_id") REFERENCES "log_index_refs" ("log_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_object_storage_refs" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_object_storage_refs" ADD FOREIGN KEY ("environment_id") REFERENCES "product_environments" ("environment_id") DEFERRABLE INITIALLY IMMEDIATE;
